substitutions:
  build_in_button: GPIO0
  build_in_led: GPIO2
  devicename: xtemplate
  friendly_name: ESP xTpl
  ota_password: "eb9ce28fa2c34a97082e8b310fa443f2" # create individual OTA password per device

esphome:
  name: $devicename
  platform: ESP32
  board: nodemcu-32s # https://docs.platformio.org/en/latest/boards/espressif32/nodemcu-32s.html#nodemcu-32s

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret esp_home_assistant_api_pw

ota:
  password: "$ota_password"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "$friendly_name Fallback Hotspot"
    password: !secret esp_home_fallback_ap_pw

captive_portal:

switch:
  - platform: restart # https://esphome.io/components/switch/restart.html
    name: $friendly_name Restart
  - platform: gpio
    pin: $build_in_led
    name: $friendly_name LED

binary_sensor:
  - platform: status
    name: $friendly_name Status
  - platform: gpio
    name: $friendly_name HW Button
    pin:
      number: $build_in_button
      inverted: True
    filters:
      - delayed_on: 10ms

# https://esphome.io/components/web_server.html?highlight=rest
#web_server:
#  port: 80

# https://esphome.io/components/status_led.html
#status_led:
#  pin: $build_in_led

## https://esphome.io/components/text_sensor/wifi_info.html
##text_sensor:
#  - platform: wifi_info
#    ip_address:
#      name: $friendly_name IP Address
#    ssid:
#      name: $friendly_name Connected SSID
#    bssid:
#      name: $friendly_name Connected BSSID
#    mac_address:
#      name: $friendly_name Mac Wifi Address
#


## https://esphome.io/components/text_sensor/version.html
text_sensor:
  - platform: version
    name: $friendly_name Version
##    hide_timestamp: True

sensor:
  - platform: uptime
    name: $friendly_name Uptime
    id: uptime_sensor

# https://esphome.io/components/sensor/uptime.html
#text_sensor:
#  - platform: template
#    name: $friendly_name Uptime
#    id: uptime_human
#    icon: mdi:clock-start

#sensor:
#  - platform: uptime
#    name: $friendly_name Uptime (sec)
#    id: uptime_sensor
#    update_interval: 60s
#    on_raw_value:
#      then:
#        - text_sensor.template.publish:
#            id: uptime_human
#            state: !lambda |-
#              int seconds = round(id(uptime_sensor).raw_state);
#              int days = seconds / (24 * 3600);
#              seconds = seconds % (24 * 3600);
#              int hours = seconds / 3600;
#              seconds = seconds % 3600;
#              int minutes = seconds /  60;
#              seconds = seconds % 60;
#              return (
#                (days ? String(days) + "d " : "") +
#                (hours ? String(hours) + "h " : "") +
#                (minutes ? String(minutes) + "m " : "") +
#                (String(seconds) + "s")
#              ).c_str();
